spring:
  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true # 웹 콘솔 사용
      path: /h2-console # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/Users/jaeseok/Documents/Yang/Dev/02.CNS/DB/test_db   # jdbc:h2:mem:testDB
    username: sa
    password:

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.misfireThreshold: 3000 # misfire라고 판단하는 기준시간
    scheduler-name: 지역스케줄러

logging:
  level:
    root: info
    yang.wind: debug

quartzdemo:
  shell:
    script-path: shell/script/ # classpath 이하에서 경로를 작성
    log-path: /Users/jaeseok/Documents/Yang/Dev/02.CNS/log/
    cmd: sh
    timeout: 60000 # 60초