
spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:postgresql://localhost:5432/kyun
    url: jdbc:oracle:thin:@172.16.22.23:3521/KSCLC1KD
    username: sscpbz
#    username: kyun
    password: roqkf01
#    password: 1234

logging:
  level:
    root: info
    wind.yang.quartzdemo: debug
    wind.yang.quartzdemo.mapper: debug

quartzdemo:
  shell:
    script-path: /home/apvtzman/yang/log/ # classpath 이하에서 경로를 작성
    log-path: /home/apvtzman/yang/log/
    cmd: sh
    timeout: 600000 # 600초

#slack:
#  url:
#    mgt: https://hooks.slack.com/services/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
#    settm : https://hooks.slack.com/services/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
