# 공통으로 사용할 어플리케이션 프로퍼티 설정
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.misfireThreshold: 3000 # misfire라고 판단하는 기준시간
      org.quartz.jobStore.driverDelegateClass: wind.yang.quartzdemo.quartz.CustomDelegate
    scheduler-name: 지역스케줄러

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:query/*.xml
  configuration:
    map-underscore-to-camel-case: true

