
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kyun
    # url: jdbc:h2:/Users/jaeseok/Documents/Yang/Dev/02.CNS/DB/test_db   # jdbc:h2:mem:testDB
    username: kyun
    password: 1234

logging:
  level:
    root: info
    wind.yang.quartzdemo: debug
    wind.yang.quartzdemo.mapper: debug

quartzdemo:
  shell:
    script-path: /Users/kyun/workspace/2020-중점추진과제/quartzdemo/src/main/resources/shell/script/ # classpath 이하에서 경로를 작성
    log-path: /Users/kyun/workspace/2020-중점추진과제/log/
    cmd: sh
    timeout: 600000 # 600초

slack:
  url:
    mgt: https://hooks.slack.com/services/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
    settm : https://hooks.slack.com/services/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
