
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/QSchedulerDB
    # url: jdbc:h2:/Users/jaeseok/Documents/Yang/Dev/02.CNS/DB/test_db   # jdbc:h2:mem:testDB
    username: cns
    password: 1234

logging:
  level:
    root: info
    wind.yang.quartzdemo: debug
    wind.yang.quartzdemo.mapper: debug

quartzdemo:
  shell:
    script-path: /Users/jongwonsong/Study/Company/quartzdemo/src/main/resources/shell/script/ # classpath 이하에서 경로를 작성
    log-path: /Users/jongwonsong/Study/Company/log/
    cmd: sh
    timeout: 600000 # 600초

slack:
  url:
    mgt: https://hooks.slack.com/services/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
    settm : https://hooks.slack.com/services/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
